RichardKnop/machinery

README.md
examples/send/send.go
examples/tasks/tasks.go
examples/worker/worker.go
v1/app.go
v1/app_test.go
v1/reflect.go
v1/tasks.go
v1/worker.go
v1/workflow_test.go

Instead of having to parse empty interfaces inside tasks, I will be using reflection to apply some magic when consuming messages so tasks can have properly typed input arguments as well as return values.

Reflection in order to avoid using empty interfaces

---

v1/brokers/amqp.go

Issue https://github.com/RichardKnop/machinery/issues/26
I'm trying to make it thread safe to allow goroutined SendTask
```
go server.SendTask(&task0)
go server.SendTask(&task1)
go server.SendTask(&task2)
```
Also I removed the connection/channel close method cause of no need in it in the case of shared connection

AMPQ. Thread-safe connection reusing

---

integrationtests/worker_only_consumes_registered_tasks_test.go
v1/brokers/amqp.go
v1/brokers/eager.go
v1/brokers/interfaces.go
v1/brokers/redis.go
v1/server.go
v1/server_test.go
v1/worker.go

When there were two parallel workers running, worker 1 with registered
task A and worker 2 with registered task B and you sent a group with
tasks A and B, there was a bug when worker 2 could pick up the A task
and fail to consume it anv vice versa which could cause SendGroup ->
result.Get() to hang.
Added integration test for such case to avoid it in the future:
integrationtests/worker_only_consumes_registered_tasks_test.go

Worker registered task consume bug fix

---

v1/brokers/amqp.go

Currently Message is acknowledged before task was actually processed.
https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp.go#L167
This contains potential message loose. Cause if task is not fully processed (f.e. worker process was killed) onError won't be called.
RabbitMQ [Reliability Guide](https://www.rabbitmq.com/reliability.html) also tips to acknowledge a message only after processing.

Ack a message after task was actually processed

---

README.md
v1/backends/redis.go
v1/backends/redis_test.go
v1/brokers/redis.go
v1/factories.go
v1/factories_test.go

Until now connecting to Redis server secured by a password was not
possible.
This PR adds an option to specify Redis broker / backend connection
string in a format `redis://password@127.0.0.1:6379`.

Allow Redis password

---

v1/worker.go

If reflection fails for a given argument, mark the task as failed and return the error.
Fixes #56.
Signed-off-by: Jorge Niedbalski <jnr@metaklass.org>

Mark the task as failed if reflection fails.

---

v1/backends/redis.go

Hi Richard,
I’ve introduced a Redis connection pool in the Backend in the same way as it is present in Broker, to avoid continuous creation/releasing of connections during asyncResult.Get().

Add pool to the redis backend

---

v1/worker.go
v1/worker_test.go

This patch makes the worker more robust to malformed input (argument list length, mismatched types, etc.)  My rationale was that these panics are solely the result of bad requests from some other domain, and there's a clear recovery path that feels better than letting the worker process crash.
Looking forward to your feedback!
Testing done:
- `$ go test -v -run TestInvalidArgRobustness ./v1`
- `$ make test`

Recover from task panics in worker.

---

v1/worker.go
v1/worker_test.go

Before this patch, the worker would advertise "interface {}" as the result type sometimes, causing downstream readers to panic.
Breaks out the construction of task results into a helper function for testability.

Handle tasks with static return type interface{}.

---

Makefile
examples/send/send.go
integrationtests/eager_eager_test.go
integrationtests/testutils.go
integrationtests/worker_only_consumes_registered_tasks_test.go
v1/backends/eager_test.go
v1/server.go
v1/worker.go
v1/worker_test.go
v1/workflow_test.go

Also ran updated `make fmt` target. Gofmt with the `-s` (simplify) option likes to elide struct names that can be inferred by the compiler, e.g. in slice literals.

Use gofmt tool instead of 'go fmt'.

---

v1/backends/amqp.go
v1/brokers/amqp.go
v1/config/config.go

amqp makes adding TLS support fairly transparent–when using `amqp#DialTLS`, it will use the supplied `*tls.Config` depending on the scheme of the protocol: `amqps://` vs `amp://`.
Tried running this against my own TravisCI but seemed to fail because of missing deps, submitting this PR in case it relies on env variables specific to your Travis setup.

Support tls amqp

---

v1/worker.go

Fixes #75 
Previously `broker.StartConsuming()` was able to kill the process due to a connection error.
Fix handles err and returns it to error channel.

Bug fix for error handling in worker

---

v1/brokers/amqp.go

Brocker amqp.open() return nil channel if amqp.DialTLS() return not empty err:
```
// Connects to the message queue, opens a channel, declares a queue
func (amqpBroker *AMQPBroker) open() (*amqp.Connection, *amqp.Channel, amqp.Queue, <-chan amqp.Confirmation, error) {
var (
conn    *amqp.Connection
channel *amqp.Channel
queue   amqp.Queue
err     error
)
// Connect
// From amqp docs: DialTLS will use the provided tls.Config when it encounters an amqps:// scheme
// and will dial a plain connection when it encounters an amqp:// scheme.
conn, err = amqp.DialTLS(amqpBroker.config.Broker, amqpBroker.config.TLSConfig)
if err != nil {
return conn, channel, queue, nil, fmt.Errorf("Dial: %s", err)
}
```
Then this will throw panic: runtime error: nil pointer dereference:
```
// StartConsuming …
```

Amqp broker: correct defer channel.Close()

---

v1/backends/result.go

With the added code, you can request the result but define also in what time that you expect the result to be ready and also the retry interval to check the status.

Avoid hammering and configure timeouts

---

v1/backends/redis.go
v1/backends/redis_test.go
v1/backends/result.go
v1/brokers/redis.go
v1/factories.go
v1/factories_test.go
v1/server.go
vendor/github.com/stretchr/testify/assert/assertion_forward.go
vendor/github.com/stretchr/testify/require/require.go
vendor/github.com/stretchr/testify/require/require_forward.go
vendor/gopkg.in/mgo.v2/bson/bson.go
vendor/gopkg.in/mgo.v2/internal/scram/scram.go
vendor/gopkg.in/mgo.v2/session.go

Redis URL format now supports "redis://password@127.0.0.1:6379/3"
If not specified, take 0 instead.

support specifying redis db

---

v1/factories.go

Sorry for the inconvenience to you.
`fmt.Errorf()` should be replaced with `errors.New()` for plain text error.

minor fix for error

---

v1/brokers/amqp.go
v1/config/config.go
v1/config/config_test.go
v1/config/testconfig.yml
v1/signatures/signatures.go

Support added to allow tasks to be redirected to a queue using task headers(Exchange type Headers). Celery sort of hand this feature(Very undocumented).
Use case want to send task to a worker running in a region/pool of workers.
Still todo
This has been issued for any discussion,
Currently use `map[string]interface{}` as the header type as it matches the type of Amqp.Table, thinking of typing this to machinery.Headers

Task Redirection By Headers

---

integrationtests/redis_socket_test.go
v1/backends/redis.go
v1/backends/redis_test.go
v1/brokers/redis.go
v1/factories.go
v1/factories_test.go

Per #89, here is support for connecting to Redis over a Unix domain socket. The approach taken here is a new URI scheme, meant as more of a stepping stone until the `Config` object allows finer-grained control over backend/broker connections.
I found various URI formats for Redis-over-socket in other projects, all slightly different, so there doesn't seem to be a standard by which to abide per se. See these for comparison or inspiration:
- https://github.com/mp911de/lettuce/wiki/Redis-URI-and-connection-details
- https://metacpan.org/pod/URI::redis
- http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html
Here I went with `redis+socket:// [passwd@] /path/to/file.sock [:/db_num]`, whereas some other projects have made use of query parameters.
I tried not to touch public …

Support for connecting to Redis socket file

---

README.md
v1/backends/amqp.go
v1/backends/redis.go
v1/backends/result.go
v1/brokers/amqp.go
v1/brokers/redis.go
v1/errors/errors.go
v1/logger/interface.go
v1/logger/logger.go
v1/logger/logger_test.go
v1/utils/retry.go
v1/worker.go

This PR adds a `github.com/RichardKnop/machinery/logger` package which is used instead of the default logger.
The following interface must be implemented:
```go
type Interface interface {
Print(...interface{})
Printf(string, ...interface{})
Println(...interface{})
Fatal(...interface{})
Fatalf(string, ...interface{})
Fatalln(...interface{})
Panic(...interface{})
Panicf(string, ...interface{})
Panicln(...interface{})
}
```
You can set your custom logger using `Set` function exported by `github.com/RichardKnop/machinery/logger` package:
```go
logger.Set(myCustomLogger)
```
All uses of stdlib logger inside the library have been replaced by:
```go
logger.Get()
```

Pluggable Logger

---

README.md

The source code was moved to `v1` I guess. So no build able source files are now available in the root directory. I get this error: 
```
package github.com/RichardKnop/machinery: no buildable Go source files
```
However `go get github.com/RichardKnop/machinery/v1` should work just fine.

Update `go get` url on readme

---

v1/brokers/redis.go

If the connection fails, return immediately. Otherwise the app will segfault a few lines later because `c` is nil.

Fix error checking for Redis broker connections

---

README.md
v1/brokers/amqp.go
v1/brokers/redis.go
v1/config/config.go
v1/config/config_test.go
v1/config/testconfig.yml

This PR is adding a config option `MaxWorkerInstances` to limit the number of concurrently executed tasks per worker. `MaxWorkerInstances=0` (default) allows an unlimited number of concurrent task executions, so the default behavior of machinery stays the same. `MaxWorkerInstances=1` essentially serializes task execution (which is a feature that I need).
Limiting is implemented for the Redis and the AMQP brokers.
All tests are passing with these changes. I would be glad if this could be merged. Let me know if there is anything else I can do to make that happen.

Limit workers

---

examples/worker/worker.go

server is redeclared in the `init` function context

fixed worker example server redeclaration

---

README.md
v1/brokers/redis.go

Redis broker now supports delayed tasks as well.
Delayed tasks are stored in a sorted set via `ZADD` command and a separate goroutines watches the `delayed_tasks` key in the sorted set via `ZRANGEBYSCORE`.

Added support for delayed tasks with redis broker.

---

v1/task.go
v1/task_test.go
v1/utils/reflect.go

This is just a preview for feedback,
Want to be able to add contexts to tasks to allow for open-tracing to be applied to contexts.
The first bit of work is to enable tasks to have contexts. To not break compatibility I have made providing a context optional.
If a task signature contains a context as its first parameter we inject a context into the task. In future work will add a context factory so people can generate there own contexts. (We could also use this to make tasks have a limited run time)

Allow tasks to have a context

---

README.md

The logging code (now) lives in `machinery/v1/log` so I've updated the README to reflect that.

Update README to reflect correct log package

---

README.md
v1/backends/amqp.go
v1/backends/eager.go
v1/backends/eager_test.go
v1/backends/interface.go
v1/backends/memcache.go
v1/backends/mongodb.go
v1/backends/redis.go
v1/brokers/amqp.go
v1/brokers/eager.go
v1/brokers/redis.go
v1/retry/fibonacci.go
v1/retry/fibonacci_test.go
v1/server.go
v1/tasks/signature.go
v1/tasks/state.go
v1/tasks/task.go
v1/worker.go

This PR aims to provide a basic retry functionality for failed tasks.
By default, failed tasks will not retry. Optionally, it will be possible to set `Signature.RetryCount` parameter to > 0 to make machinery retry failed tasks.
Progress:
- added a new `RETRY` state
- added `RetryCount` parameter to signature.

Retry Tasks

---

v1/common/redis.go

First of all, thanks for writing Machinery, it's been a pleasure to use.
We've been running Machinery to schedule tasks for execution at a later time, using Redis as a broker. After running for a couple of days without restarting we have noticed no new tasks being picked up, even though they are scheduled for execution at those times. We don't get any errors, it just stops consuming.
I suspect that this could happen due to the redis connection hanging on read or write, and I figured it would be a good idea to set a timeout on those.

Set read and write timeouts on the redis connection

---

README.md

Hi! I corrected some lines on configuration example in README.
`Conifg.AMQP` value should be `*AMQPConfig` type and `DefaultQueue` is field of `Config` not `AMQPConfig`.

Fix outdated config example in README.md

---

README.md
example/machinery.go
integration-tests/amqp_amqp_test.go
integration-tests/amqp_memcache_test.go
integration-tests/amqp_mongodb_test.go
integration-tests/amqp_redis_test.go
integration-tests/eager_eager_test.go
integration-tests/redis_memcache_test.go
integration-tests/redis_mongodb_test.go
integration-tests/redis_redis_test.go
integration-tests/redis_socket_test.go
integration-tests/suite_test.go
integration-tests/worker_only_consumes_registered_tasks_test.go
v1/brokers/amqp.go
v1/brokers/eager.go
v1/brokers/interfaces.go
v1/brokers/redis.go
v1/config/config.go
v1/config/env_test.go
v1/config/file_test.go
v1/config/testconfig.yml
v1/server.go
v1/tasks/workflow.go
v1/worker.go

Hi,
as described in my comment in #111 I refactored the global `MaxWorkerInstances` config into a separate Worker attribute.
This way we can set different concurrencies for different workers. This is already part of many other worker packages.
Unfortunately this is a breaking change, so I will let you decide if and how you want to integrate it.
Cheers

Add support for concurrency per worker

---

v1/brokers/redis.go
v1/server.go
v1/worker.go

Hi, I think I found some bugs, and tried to fix them.
Bug1:  If we send a group with many tasks, and the sending process is not  finished. While some of the previous sent tasks have finished, they will  use the getStates() function to check the group status and will  return an error. This will lead the "brokers/redis.go" consume()  function exit and leave the other tasks stay in the Redis forever. 
Bug2:The SendGroup() function has no pool mechanism, which will cause crash when there are many tasks in one group.
Bug3: brokers/redis.go consume() function (about L200) , there is a dead lock condition.If there some routines failed, they will wait at "errorChan <- err" . The main process will get a err from one of the routines, and before return , it will wait at   "defer wg.Wait()". This is …

I found some bugs

---

integration-tests/suite_test.go
v1/server.go

Currently there is a bug in SendGroup pooling logic which means all tasks will be sent synchronously irrespective of the concurrency parameter sent to the method.
See this issue: https://github.com/RichardKnop/machinery/issues/172

Fix pool logic to handle concurrency in SendGroup call.

---

v1/server.go

Hi, I found a problem in the SendGroup.
The length of errorsChan in SendGroup function is 1. Once more than one error happen, the main program or some routine will block. 
The max number of errors can happen in this section is 2*len(group.Tasks). So I change the size to it.
I'm not sure if it is very good. So please confirm it. Thanks very much.

fix err chan size in server.go

---

v1/worker.go

Playing around with machinery chains, I found that in some cases appending the result value of a task at the beginning of the arguments slice used to execute the next task, can result on unexpected issues if the position of the arguments is important for the function and the result of the previous one is not being considered or is wanted as an optional argument.
So, I propose to change the append order of those arguments or maybe have an optional parameter to allow the user to choose if they want them at the beginning or the end of the slice ?
Let me know your thoughts.
Thanks

change order of appended arguments on success

---

example/machinery.go
example/tasks/tasks.go
v1/backends/async_result.go
v1/brokers/amqp.go
v1/brokers/redis.go
v1/worker.go

See: https://github.com/RichardKnop/machinery/issues/194
This PR fixes the worker quitting logic. When there are running tasks and you call `worker.Quit()` method, the process will wait for all running tasks to be processed first before shutting down.
Open to suggestions how to improve this. Should it be made optional? Maybe have an argument to ignore running tasks and quit worker abruptly?
Or if you do `Ctrl+C` two times it should abort without completing running tasks?

Wait for running tasks to finish when quitting a worker.

---

v1/brokers/amqp.go
v1/brokers/errors.go
v1/brokers/redis.go
v1/config/env.go
v1/config/file.go

Delayed tasks with Redis broker now get routed to a correct queue based on routing key and not just passed to the current worker instance which meant delayed tasks with other than default queue name as routing key would not work.

Redis Delayed Tasks Fix

---

v1/brokers/amqp.go

Right now using AMQP is not reliable, because you're perform Ack before worker processing. 
For example if application got SIGKILL, worker will be never restarted.
I guess it is incorrect. What do you think?

Perform amqp ack after worker processing

---

v1/backends/backend.go
v1/brokers/amqp.go
v1/brokers/broker.go
v1/brokers/interfaces.go
v1/brokers/redis.go
v1/factories.go

Current implementation had a bug when AMQP related settings were left in the config file, it would try to use AMQP binding key and hence `AdjustRoutingKey` would set routing key to the binding key even for Redis broker. That should only happen for AMQP broker.

Fixed AdjustRoutingKey for Redis broker

---

Makefile

CI isn't reporting the correct results.  Because of the for loop in `make test` and `make test-with-coverage`, an error is only returned if the last suite fails.  This change will cause the build to fail if a test fails in any package.
In the most recent travis builds, there are test failures that don't result in the build failing.
https://travis-ci.org/RichardKnop/machinery/jobs/311917478#L586-L591

Make test results

---

v1/brokers/broker_test.go

TestAdjustRoutingKey is failing on master.  I believe this is a problem with the test and not the production code.  
I split the test up into subtests to help keep track of which part is failing.  The section that was failing is in the "with binding key" subtest.  I fixed it by making the broker an AMQPBroker.  That allows it to get past the if statement below.  
This is only a fix if my assumption is correct that only AMQPBrokers should make it past the `IsAMQP` test.
https://github.com/RichardKnop/machinery/blob/f0e7c029c37ba02297b60903237ae9581955b339/v1/brokers/broker.go#L100

Fix broker_test

---

v1/config/env.go
v1/config/file.go

I found that when other brokers were used, config of AMQP was still in config. So if I don't set ```RoutingKey``` in the signature, then ```AdjustRoutingKey``` will be called, which will go into 
```
if IsAMQP(b) && b.GetConfig().AMQP != nil && b.GetConfig().AMQP.ExchangeType == "direct" {
// The routing algorithm behind a direct exchange is simple - a message goes
// to the queues whose binding key exactly matches the routing key of the message.
s.RoutingKey = b.GetConfig().AMQP.BindingKey
return
}
```
So the ```default_queue``` in config file will not be used.

When config doesn't has AMQP, AMQP still shows up in default config

---

v1/config/config.go
v1/worker.go

This allows users to define if they want to use machinery's built in signal handling or not, there are cases where users might not want to rely on machinery to do signal handling

Adding config option to skip signal handling

---

.gitignore
docker-compose.test.yml
integration-tests/sqs_mongodb_test.go
v1/backends/mongodb.go
v1/tasks/state.go

- use findAndModify where lock is false to avoid update race conditions & simplify lock check
- use findAndModify in lockGroupMeta

ISSUE-232: prevent multiple chord triggers w/ concurrent workers

---

README.md
v1/brokers/errors.go
v1/tasks/errors.go
v1/tasks/task.go
v1/tasks/task_test.go
v1/worker.go

You can now return `tasks.ErrRetryTaskLater` from your task and specify duration after which the task should be retried, e.g.:
```go
return tasks.NewErrRetryTaskLater("some error", 4 * time.Hour)
```
This is useful so you can implement a custom retry logic and not rely on the default behaviour when task is retried using a Fibonacci sequence as a backoff function.

Added tasks.ErrRetryTaskLater

---

integration-tests/eager_eager_test.go
v1/backends/amqp.go
v1/backends/eager.go
v1/backends/eager_test.go
v1/backends/memcache.go
v1/backends/redis.go
v1/brokers/amqp.go
v1/brokers/aws_sqs.go
v1/brokers/eager.go
v1/brokers/redis.go
v1/tasks/reflect.go
v1/tasks/reflect_test.go
v1/tasks/signature.go

This is in order to not lose any precision when dealing with big integers.
JSON/JavaScript only support floating point numbers so any time we marshal a signature to JSON message to send it over message queue to a worker, it needs to be decoded on the other side.
When decoding into `interface{}`, this would cause problems with large integer and unsigned integers, namely losing of precision. This problem is solved by using https://golang.org/pkg/encoding/json/#Decoder.UseNumber

Use json.Number when unmarshaling JSON

---

example/machinery.go

Otherwise you'll get a dangling trace that is not associated with
the rest of the spans in the example.

fix(example): make split example use traced function

---

v1/brokers/aws_sqs.go

Addresses https://github.com/RichardKnop/machinery/issues/253 for SQS

Only delete SQS messages after at task successfully processes the message

---

README.md
v1/brokers/aws_sqs.go
v1/config/config.go

we discovered that the sqs broker was using ResultsExpireIn as the receive message value for "VisibilityTimeout", which defaults to 0 and overrides the visibility timeout setting on the queue which has the side effect of processing a task multiple times before deletion (https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-visibility-timeout.html)
I've replaced the sqs broker's use of ResultsExpireIn with an optional VisibilityTimeout pointer field on SQSConfig so that when nil, the queue's visibility timeout setting is used.

sqs visibility-timeout config option, readme update

---

v1/brokers/aws_sqs.go

fixing a bug in the err handling of processed tasks.
current behavior:
a task is attempted deletion when process returns an error
expected behavior: 
a task should be attempt deletion when process does not return an error

fix sqs task process deletion

---

v1/common/redis.go
v1/factories.go
v1/factories_test.go

Fix `NewPool` Logic and Rewrite `ParseRedisURL` using `url.Parse`(It's probably more robust to just use url.Parse and extract all the info from the URL)
Signed-off-by: duyanghao <1294057873@qq.com>

Fix NewPool and Rewrite ParseRedisURL

---

v1/backends/redis.go
v1/brokers/redis.go
v1/common/redis.go
v1/config/config.go

At some time, we need to limit the redis pool size and number of idle connections to support different application scenarios. This PR is to export the arguments of redis pool and connection. Machinery uses the default redis config If you don’t need to customize the arguments of redis pool.

add redis config

---

v1/brokers/redis.go
v1/common/redis.go
v1/config/config.go

Hi,
As of now, using redis as a backend, delayed tasks are implemented by polling every 20 milliseconds for tasks to add to worker queues for consumption. This can represent up to 200 read ops / second on redis, which is I think a bit heavy, especially for people who don't use delayed tasks or who don't need sub-second precision for the execution of their delayed tasks. This PR makes this polling period configurable, while keeping the default to 20  ms, therefore not changing the current behaviour.

Make delayed tasks polling period configurable for the redis backend

---

v1/brokers/amqp/amqp.go
v1/worker.go

Currently, when you **Publish** a message (https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L97) the function `b.AdjustRoutingKey(signature)` is called. The `signature.Routingkey` is used to connect/publish the message (https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L123); however when the message has a delay (https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L108) the `signature.Routingkey` property isn't used to define where to send it when the delay is over.
As the property `signature.RoutingKey` was set in the function `b.AdjustRoutingKey(signature)`, the delay function should use the value set previously instead of trying to retrieve it directly from the binding/routing key …

Adding support for routingKey in delays

---

v1/brokers/amqp/amqp.go

On our internal project, we found that creating a new connection for each machinery task was gradually overloading our feeble rabbitmq server (there may be other systemic problems in our codebase that lead to this, but this was one of the hypothesised causes).
This PR attempts to also address issue https://github.com/RichardKnop/machinery/issues/326. 
The implemented solution uses a simple mapping to cache connections on each queue. The connections are not closed after the task completes, allow the caller to reuse the connection with later `Publish()` calls.
Some potential issues and concerns I have with my patch (which I would appreciate input on)
1. I am not sure whether the mutex is necessary. The hypothesised race condition occurs when two goroutines attempt to GetOrOpenConnection at …

Added amqp connection caching

---

v1/common/broker.go

Fix for [issue 346](https://github.com/RichardKnop/machinery/issues/346). Worker is now using stopChan in a non-blocking mode.

Broker is now using stopChan in a non-blocking mode

---

go.mod
go.sum

Closes #361 
Removed `github.com/garyburd/redigo v2.0.0+incompatible // indirect` from `go.mod` and run `go mod tidy`.

Use garyburd/redigo v1.6.0

---

v1/brokers/amqp/amqp.go

In this [PR](https://github.com/RichardKnop/machinery/pull/345) "connection cache" was added for main tasks and was also added for delay tasks, however, delay queues might have multiple names like "delay.10945997.exchange.task". Check [L195](https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L195) and [L337](https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L337), the new approach of caching connections is creating many open connections. In our case, it consumes all the available connections (max 20) for developer plans in [cloudamqp](https://www.cloudamqp.com/plans.html) and it doesn't permit to open new connections to store messages.
The problem is only for delay tasks/queues.

Revert amqp connection caching when is a delay task (queue)

---

example/machinery.go
v1/worker.go

It is a way for adding hooks before and after the tasks are called.
This is useful for retrieving information and metrics.
```go
worker.SetPreTaskHandler(func(signature *tasks.Signature) {
counter.WithLabelValues(signature.Name).Inc()
})
```

feat(hooks): add pre-task and post-task hooks

---

v1/brokers/sqs/sqs.go
v1/tasks/signature.go

Introduce a new attribute 'BrokerMessageGroupID' on task.Signature that should be used for specifying sqs.MessageGroupId when submitting tasks to a FIFO SQS queue.
When sending a message to FIFO queue if no `BrokerMessageGroupId` attribute is specified, `m.server.SendTask` will return error like:
`Publish message error: please specify BrokerMessageGroupId attribute for task Signature when submitting a task to FIFO queue`
To submit a Job to Fifo sqs queue, task Signature must specify `BrokerMessageGroupId` attribute.
e.g.
```
task := tasks.Signature{
Name: "name",
Args: []tasks.Arg{
{
Name:  "payload",
Type:  "string",
Value: "payload",
},
},
BrokerMessageGroupId: "sqs-group",
}
```

Do not use Machinery's GroupUUID to set SQS MessageGroupID attribute.

---

v1/brokers/sqs/sqs.go
v1/brokers/sqs/sqs_export_test.go
v1/brokers/sqs/sqs_test.go

When using SQS broker make sure worker started with server.NewCustomQueueWorker() listens on custom queue specified as function argument and not on default queue specified in config
cc @RichardKnop  this fixes #367

367 Fix NewCustomQueueWorker() functionality with sqs broker

---

v1/brokers/sqs/sqs.go

Make sure when using custom queue worker with SQS broker, worker  attempts to delete message from Custom Queue which was used to start the worker and not the default queue from config.
Related to: https://github.com/RichardKnop/machinery/issues/367

367 Fix task deletion error when using custom queue with SQS Broker

---

v1/brokers/amqp/amqp.go
v1/brokers/eager/eager.go
v1/brokers/gcppubsub/gcp_pubsub.go
v1/brokers/iface/interfaces.go
v1/brokers/redis/redis.go
v1/brokers/sqs/sqs.go
v1/server.go

Passing the context when `Publishing`  jobs allows tracing to be all under one trace. This change is mostly useful for `PubSub` and `SQS` right now since they are the only ones tracing requests going out.

Add context to Publish method for tracing purposes.

---

v1/brokers/gcppubsub/gcp_pubsub.go

Concurrency parameter was ignored and receiving was only done in one go routine. This PR adds the ability to define the number of Go Routines that should process incoming messages.

Make sure PubSub consumes in concurrency number of Go routines.

---

v1/backends/redis/redis.go
v1/brokers/redis/redis.go

This PR fixes a few things:
1. The broker and backend's `open` function was not thread safe and since the `pool` and `redsync` instance were initialized only once I wrapped them in a `sync.Once`
2. The timer in the broker's `StartConsuming` method often slept for either 0 or 100 milliseconds which first of all adds a strain to the Go scheduler. After every timer tick the broker would send a `BLPOP` to Redis with a timeout of 1 millisecond and if it doesn't find an item it would wait another 100 milliseconds and do the same. There's no point in doing this constant back and forth which eats up the server runinng machinery's CPU and Networking resources as well as Redis'. Instead, now we launch X amount of `BLPOP` operations with a timeout of 1 second, where X is the configured concurrency. …

Redis backend/broker performance and data race fixes

---

v1/backends/redis/redis.go

This fixes a bug where the group key TTL is reset to -1 by the SET call. We need to reset it back to our desired expiry after the SET call.
A future improvement could be to pass the EX option to SET instead of always doing a separate EXPIREAT for all keys.

Redis backend - reset group expiry in TriggerChord

---

v1/tasks/task.go
v1/tasks/task_test.go
v1/worker.go

Rationale behind this PR:
I want to:
1. able to interrupt/cancel a running job.
2. running job able to send progress
both of these require the job func to know the task id so that I can save status to a db. e.g. Redis
I could make it an argument in the task function and send the task id on `Send`, but I reckon having the signature in the context make more sense.
See example: https://github.com/jackielii/process

inject signature into the context

---

integration-tests/sqs_amqp_test.go
v1/backends/amqp/amqp.go
v1/backends/amqp/amqp_test.go

The AMQP backend should choose correct URL to connect to.
For now some cases should not work.
E.g., Use SQS as broker and AMQP as result backend.

Support for using non-AMQP as broker and AMQP as result backend

---

v1/brokers/amqp/amqp.go

Before this pr, the routing key was bound to the default binding key.
This resulted in spurious bindings being created.
This pr changes the call to GetOrOpenConnection to use the defaultqueue vs the routing key as a queue to lookup and bind.
Note that it doesn't seem like this queue element isn't used by this code at all, so correctness of the rest of the funciton is preserved.
Because we bind the default queue to the default binding key, we also prevent any other unintentional behaviour (as the integrity of the maintained connections is not broken)

Apply binding to default queue

---

v1/config/config.go

The default expire time is 1day, not 1hour.

the default expire time is 1 day, not 1 hour

---

v1/brokers/redis/redis.go
v1/common/broker.go
v1/common/broker_test.go

Done same way it is done in AMPQ broker here - https://github.com/RichardKnop/machinery/blob/master/v1/brokers/amqp/amqp.go#L261 
Now Redis broker applies Worker concurrency param only to consumption from Redis, not to task execution, every task just gets it's own goroutine without limit which leads to unbounded growth of tasks Worker is executing if single task is considerably heavier than consumption from Redis.
Changed that so that only Worker.Concurrency number of tasks can be executed at a time.

Limit Redis broker task execution concurrency by config too + fix shutdown panic

---

v1/brokers/amqp/amqp.go

As discussed in #419 , before this PR, it is unable to setup a new queue binded to the direct exchange with a expected binding key.
For non direct type exchange, it acts exactly as before.
For direct type exchange:
1. If no routing key set in the signature, `AdjustRoutingKey` sets it to `b.GetConfig().AMQP.BindingKey`, in this PR, `bindingKey = signature.RoutingKey` ensures that it behaves like `bindingKey = b.GetConfig().AMQP.BindingKey`;
2. For cases that routing key is set in the signature, it always use passed routing key as binding key, so every queue will have a independent binding to the exchange and it matches the routing key exactly.
So I believe this PR preserves the correctness of rest code.

use routing key as both queue name and binding key

---

v1/brokers/gcppubsub/gcp_pubsub.go

Pubsub was not terminating correclty when SIGTERM was received. It was exiting as soon as it was received.
Pubsub docs say that its best practise to also run any processing code in the Receive function, has been refactored to take that into account

Fix pubsub termination

---

v1/brokers/amqp/amqp.go
v1/config/config.go

As discussed in #425 , before this PR, it is impossible to set the autodelete param of delayed queues.
If nobody sets this value to `true`, it acts exactly as before.

AMQPConfig AutoDelete 

---

v1/brokers/sqs/sqs.go
v1/brokers/sqs/sqs_export_test.go
v1/brokers/sqs/sqs_test.go

Fixes an issue with SQS Broker where it receives more messages than concurrency specified, because of the fact that while receiving it was not checking whether already received job is done or not, instead it fetches next task as soon as task is assigned to a worker goroutine, this causes Machinery to move more messages into "Inflight" in SQS than the concurrency specified. 
E.g. Before fix if worker is started with concurrency of 1, Machinery will receive two messages from SQS ( one after other) but since concurrency is 1 will only be processing one message at a time.

Fix issue with SQS broker, where it receives more messages than it can consume at a given time

---

v1/brokers/sqs/sqs.go
v1/tasks/signature.go

Fixes #433 
When using SQS broker there is no way to get hold of SQS message's ReceiptHandle, this PR adds a new property `SQSReceiptHandle` to `tasks.Signature` which gets populated by SQS broker when consuming a message

Re:433 Expose SQS ReceiptHandle in task signature

---

integration-tests/redis_redis_test.go
v1/brokers/redis/redis.go
v1/common/broker.go
v1/common/redis.go
v1/config/config.go
v1/factories_test.go

Fix #439:
1. When launching Redis worker and then shutdown immediately, StopConsuming() could try to close(b.StopChan) BEFORE b.StopChan is initialized inside StartConsuming().
Solution: Initialize field when object is being initialized.
2. When using Redis broker, nextTaks() usings BLPOP can block for a long time.
Solution: Make timeout value configurable.
See also: PR #406, #443

Fix #439 race condition and slow shutdown with worker

---

v1/brokers/gcppubsub/gcp_pubsub.go

Currently it's not possible to publish to a different topic other than the default one for GCP Pubsub, when the routing key is set on the signature.
This ensures the correct routing key (set after `b.AdjustRoutingKey()` is called), is used when publishing.

Fix pubsub routing key.

---

v1/brokers/errs/errors.go
v1/brokers/redis/redis.go

This happens to me when I have an e2e test fixture setup as follows:
- `miniredis.Run()`  // setup
- `worker.Launch()`
- short test -- takes almost no time
- `worker.Quit()` // teardown
- `miniredis.Close()`
As `worker.Launch()` (or `LaunchAsync()`) starts redis.StartConsumer() in a goroutine, it is possible for `worker.Launch()` to return immediately and teardown code to be executed.
If `worker.Quit()` has been called, then it is unlikely for the Redis ping result to matter. So modified the code to return an appropriate error for client side checking.

Enhance error handling for a race condition in Redis broker

---

go.sum

run `go mod tidy` to minify go.sum, `git.apache.org/thrift` has been removed

minify go.sum

---

v1/config/config.go

Change default DelayedTasksPollPeriod from 20 ms to 500 ms

Fix #465 - Sync DelayedTasksPollPeriod in config.go/redis.go

---

v1/common/redis.go
v1/config/config.go

The default Machinery settings was opening/closing lots of new Redis connections every time SendTask() is called. This lead to major CPU load for Redis and eventually exhaust the max number of client connections as the Redis process has trouble keeping up with all the open/close connections.

Fix #468 - Optimize RedisConfig for connection pool

---

v1/brokers/amqp/amqp.go

The AMQP broker currently logs all message bodies at `INFO` level, which can cause a prohibitive amount of noise for those users who would like to enable other `INFO` logs.
This sort of logging is best handled at a `DEBUG` level (as it is in the Redis broker). 
This PR changes the relevant log level to `DEBUG`.

Change log level within amqp broker

---

README.md
v1/backends/redis/goredis.go
v1/brokers/redis/goredis.go

Try to support Redis cluster with a password,  for both broker and backend.
```
broker: 'redis://pass@host1:port1,host2:port2,host3:port3'
result_backend: 'redis://pass@host1:port1,host2:port2,host3:port3'
```
How to test
REDIS_URL_GR=pass@localhost:7000,localhost:7001 go test

Feat: Support redis cluster with password

---

v1/brokers/eager/eager.go
v1/brokers/iface/interfaces.go
v1/brokers/redis/goredis.go
v1/brokers/redis/redis.go
v1/brokers/sqs/sqs.go
v1/common/broker.go

Some broker implementations (like redis) use a separate queue for
delayed tasks. This commit exposes the contents of that queue via the
Broker interface so callers can see which tasks are scheduled with a
delay.

Expose delayed tasks via the broker

---

v1/brokers/sqs/sqs.go

Delete message from SQS if message body is not valid JSON, could happen when producer is not based on machinery. If we don't delete the message, message will stay in "inflight", will keep getting retried after visibility timeout and will ultimately end up in DLQ

Delete SQS message if unmarshalling fails

---

v1/backends/dynamodb/dynamodb.go

This PR address Issue https://github.com/RichardKnop/machinery/issues/525
Since the data fetched the result backend (DynamoDB in this case) is used to lock objects and to determine the completion of Groups, we need strongly consistent reads. Reading stale data causes bugs like the one mentioned in the above issue.
DynamoDB does not use strongly consistent reads by default unless explicitly asked for. This PR makes read requests explicitly ask for consistent data.

[DynamoDB] Use uses strongly consistent reads

---

v1/backends/dynamodb/dynamodb.go

Adding some more identifying information to the messages so that they are a bit more useful.
Ex: `Group meta locked, waiting` vs
`Group [group_abcd-efgh] locked, waiting`

[DynamoDB] Small improvements to error messages

---

README.md
v1/backends/dynamodb/dynamodb.go
v1/backends/dynamodb/dynamodb_export_test.go
v1/backends/dynamodb/dynamodb_test.go
v1/tasks/state.go

This PR implements setting the TTL value for DynamoDB records based on the `ResultsExpireIn` config value. (Issue https://github.com/RichardKnop/machinery/issues/518)
- The TTL value is set only on terminal task states (SUCCESS & FAILURE).
Because of retries, sometimes task completion (success or failure) may take longer than the configured expiration time. So we should not set TTL on non-terminal states (PENDING, RECEIVED, STARTED, RETRY)
- Added tests.
Provided method overrides to change the behavior of DynamoDB client. Tests assert that the correct state and TTL values are set for the given task.

[DynamoDB] Support ResultsExpiresIn

---

v1/tracing/tracing.go

Fix the issue that put taskUUID in groupUUID tag in task span.

fix: wrong groupUUID in task span

---

integration-tests/redis_redis_test.go
v1/brokers/amqp/amqp.go
v1/brokers/amqp/amqp_concurrence_test.go
v1/brokers/iface/interfaces.go
v1/brokers/redis/redis.go
v1/worker.go
v2/worker.go
v2/worker_test.go

Adding support for `preConsumeHandler` to perform checks and then allow to pop messages from queues. This is in reference to issue #532 
Usage:
```go
server, _ := machinery.NewServer(config)
worker := server.NewWorker("test_worker", 0)
worker.SetPreConsumeHandler(func(w *machinery.Worker) bool {
// perform checks; like rate limits
// if allowed return true, else false
return true
})
worker.Launch()
```

Add support for preConsumeHandler in worker

---

v1/worker.go
v2/worker.go

Does an early return if the completed task is not part of a chord. Fetching all the task states in the group is unnecessary.

[Worker] Early return when there is no chord callback

---

v1/worker.go
v2/worker.go

Logs the error when fetching the task states for a group fails.

[Worker] log when fetching group task states fail

---

v1/worker.go
v2/worker.go

Using WaitGroup to prevent the exit of broker consumption goroutine when Unix signal is being handled

Worker graceful shutdown

---

v1/brokers/redis/redis.go

The redis broker sometimes shuts down before currently processing tasks are complete. This typically is not an issue except when these running tasks wish to publish other tasks before completing. Since the `StopConsuming()` method closes the Redis pool, publishing of new tasks fail as well.
This PR waits for the tasks currently being processed before closing the redis pool.

[Redis Broker] Wait for currently processing tasks to finish before closing the redis pool

---

v1/brokers/redis/goredis.go
v1/brokers/redis/redis.go

According to the README:
> Use the second parameter of `server.NewWorker` to limit the number of concurrently running
> worker.Process() calls (per worker). Example: 1 will serialize task execution while 0 makes
> the number of concurrently executed tasks unlimited (default).
This change will set the concurrency to 2 * num CPUs when concurrency = 0. While it isn't "unlimited", it is neverthe a practical choice for most workloads (mixed CPU, I/O) and better than 1. This change should make the behavior more consistent with the doc.
Should also fix #535

Fix #529 - Set Redis default concurrency when value is 0

---

v1/config/config.go
v1/config/file_test.go
v1/config/testconfig.yml

Re-apply 342ef9fe; also update test to include other yaml options.

Fix typo in config.go

---

v1/brokers/redis/redis.go

When `DISCARD` is called without calling `MULTI` it gives following error:
`(error) ERR DISCARD without MULTI`
Such use of `DISCARD` also seems to be causing issues with blocking commands on certain Redis machines where blocking pop(i.e. `BLPOP`) does not timeout.

Use UNWATCH when MULTI is not called

---

v1/brokers/redis/redis.go

Currently, Redis broker pops `concurrency+2` extra messages from the queue and keeps it in memory while processing previous messages. Now if the worker process shuts down abruptly during the processing due to unforeseen circumstances, then `concurrency+2` messages are lost forever. 
Also, during graceful termination, the already popped messages are first processed and only then the worker shuts down. This leads to higher time for graceful terminations and one has to set the graceful termination timeout period to a higher value.
This PR makes changes to enqueue those messages back into the queue once a termination signal is received. This will bring down the time for graceful termination considerably.

Push already popped messages back into queue during graceful termination

---

v1/backends/result/async_result.go

Found a bug in `GetWithTimeout` for `chainAsyncResult` where it was using the wrong `err` object named `errcurr` but didn't return that error. Fixing it for you since it bugged me

chain async GetWithTimeout should use correct err

---

v1/brokers/redis/redis.go

more than concurrency count tasks would be gotten in former code, thus add a channel for receiving previous task end signal, which would block taking task from redis, solving the problem mentioned in #559

ensure consuming blocked by previous task (#559)

---

v1/common/broker.go

Add read lock when access registerdTaskNames field.

v1/common/broker.go: add read lock for registerdTaskNames

---

v1/brokers/redis/goredis.go
v1/brokers/redis/redis.go

A small fix so I have a race condition when initializing tests when I run them in parallel with several instances of machinery.

Fix default DelayedTasksKey in config

---

v1/brokers/redis/goredis.go

This commit fixs #633
When start more than one worker, a failed task would be put in delayed queue and consumed more than once by the workers, with goredis as backend.
This is mainly because currently no transaction provided for ZRevRangeByScore and ZRem  in nextDelayedTask， and this patch fixes the issue, with the correct way to make use of Redis Watch

fix: fix failed task retry repeated when there are multi workers

---

example/v1/amqp/main.go
example/v1/redis/main.go
example/v2/amqp/main.go
example/v2/go-redis/main.go
example/v2/redigo/main.go
v1/locks/redis/redis.go

To fix the issue with missing context arguments to redis calls in `/v1/lock/redis/redis.go`, I simply pulled the context out of the Redis client and passed in where needed.

Fix issues #127 and #126

---

v1/locks/redis/redis.go

The previous code would fail to parse a password from a connection string if the password was empty. This uses the code used in, e.g., https://github.com/RichardKnop/machinery/blob/master/v1/brokers/redis/goredis.go#L43, as well as the backend.

Update Redis lock connection string parsing.

---

v1/backends/redis/goredis.go
v1/brokers/redis/goredis.go
v1/config/config.go
v1/factories.go

With the cluster mode flag, we can explicitly use Redis cluster client,
instead of universal client controlling by Redis universal client logic.
So it can support a single configuration endpoint for Redis
related issue: https://github.com/RichardKnop/machinery/issues/701

feat: add redis cluster mode flag in redis config

---

v1/locks/eager/eager.go
v2/locks/eager/eager.go

`(1)` read lock won't exclude other read locks. it's useless here.
Although `register.m` is `sync.Map`, but reading and writing are two operations. If two goroutines read empty `register.m` at the same time, exists will be false. Then the two goroutines will get lock at the same time.
```go
func (e *Lock) Lock(key string, value int64) error {
e.register.RLock() // (1) read lock
defer e.register.RUnlock()
timeout, exist := e.register.m.Load(key) // (2) read
if !exist || time.Now().UnixNano() > timeout.(int64) {
e.register.m.Store(key, value) // (3) write
return nil
}
return ErrEagerLockFailed
}
```
When run go test with race flag `go test -race ./locks/eager`, will got these warning.
```
==================
WARNING: DATA RACE
Read at 0x00c0001152f0 by goroutine 7: …
```

fix: make sure eager lock is concurrent safe

---

v1/brokers/gcppubsub/gcp_pubsub.go

According to PUBSUB official client, NumGoroutines is not enough to respect concurrency
https://pkg.go.dev/cloud.google.com/go/pubsub#ReceiveSettings.NumGoroutines
```
NumGoroutines does not limit the number of messages that can be processed
concurrently. Even with one goroutine, many messages might be processed at
once, because that goroutine may continually receive messages and invoke the
function passed to Receive on them. To limit the number of messages being
processed concurrently, set MaxOutstandingMessages.
```

Respect concurrency in GCP

---

v1/tasks/reflect.go
v1/tasks/reflect_test.go
v2/tasks/reflect.go
v2/tasks/reflect_test.go

Such as 1<<64 - 1, math.MaxInt64 + 1, etc.
Sending these values to task arguments will cause a panic. These values are legal golang uint64 values.

fix: overflow when parsing a huge uint64 number

---

go.mod
go.sum
v1/backends/amqp/amqp.go
v1/brokers/amqp/amqp.go
v1/brokers/amqp/amqp_concurrence_test.go
v1/common/amqp.go
v2/backends/amqp/amqp.go
v2/brokers/amqp/amqp.go
v2/brokers/amqp/amqp_concurrence_test.go
v2/common/amqp.go
v2/go.mod
v2/go.sum

**Scope**
This Pull Request aims to update the AMQP SDK from the non-maintained streadway version to the actively maintained amqp091-go version. The update is necessary to ensure compatibility with the latest features, improvements, and bug fixes available in the amqp091-go library.
**Changes Made**
Dependency Update:
Updated the AMQP dependency to use the amqp091-go library.
Removed references to the non-maintained streadway package.
Code Modifications:
Reviewed and adjusted code that may be affected by the changes in the SDK.
Ensured compatibility with the new API provided by amqp091-go

AMQP:update amqp sdk from non maintained streadway to amqp091-go

---

README.md
v1/brokers/amqp/amqp.go
v1/config/config.go
v2/brokers/amqp/amqp.go
v2/config/config.go

Summary:
This pull request introduces a configurable option to specify a custom delayed queue in the AMQP configuration. The goal is to allow users to have greater flexibility in handling delayed tasks without the need to create multiple delayed queues in Machinery.
Changes:
Added a new configuration parameter DelayedQueue to the AMQP configuration.
The DelayedQueue parameter allows users to set a custom name for the delayed queue.
Motivation:
Currently, Machinery create multiple queue when we choose task with retry or delayed task. This limited the scaleability when we have millions of delayed task.
Usages:
This feature can be used if env variables AMQP_DELAYED_QUEUE is set else it will continued with current approach in both v1 and v2.

AMQP: added custom delayed queue config

---

v2/backends/redis/goredis.go
v2/brokers/redis/goredis.go
v2/config/config.go
v2/locks/redis/redis.go

With Redis cluster configurations that have only one endpoint (AWS ElastiCache for example), the go-redis `UniversalClient` will create `Client` object, not `ClusterClient`, which will not be able to execute commands on cluster nodes.
This pull request added `ClusterEnabled` config in `RedisConfig` struct to enable configuring support for Redis cluster specifically.

Support Redis cluster with single endpoint configuration

---

v1/brokers/amqp/amqp.go
v2/brokers/amqp/amqp.go

This pull request addresses an issue related to the handling of AMQP based task messages when a task is not registered with the worker, and `IgnoreWhenTaskNotRegistered` is set. The existing logic is adjusted to correctly NACK the message with `requeue=false` in these scenarios.
- Adjust the logic to properly NACK the AMQP message with `requeue=false` when `IgnoreWhenTaskNotRegistered` is true.
This fix ensures consistent and correct behavior in handling AMQP messages, especially in scenarios where tasks are not registered, and `IgnoreWhenTaskNotRegistered` is configured.

AMQP: nack the message with requeue false when IgnoreWhenTaskNotRegistered

---

v2/backends/mongo/mongodb.go

this pr https://github.com/RichardKnop/machinery/pull/817 introduced a different bug - retrieving results from mongodb fails now, because the TaskState.TTL field is an int64, not a time. Fixing by renaming the field with ttl index in mongodb document

fix ttl field for mongo backend
