.travis.yml, README.md, v1/backends/amqp.go, v1/backends/memcache.go, v1/backends/memcache_test.go, v1/backends/result.go, v1/factories.go, v1/factories_test.go, v1/server.go, v1/worker.go, v1/workflow.go
Added support for Memcache result backend.
```go
cnf := config.Config{
// ...
ResultBackend: "memcache://10.0.0.1:11211,10.0.0.2:11211",
// ...
}
```
=> Memcache Result Backend

v1/backends/amqp.go, v1/backends/amqp_test.go, v1/backends/interfaces.go, v1/backends/memcache.go, v1/backends/memcache_test.go, v1/backends/result.go, v1/backends/states.go, v1/backends/states_test.go, v1/brokers/amqp.go, v1/brokers/interfaces.go, v1/server.go, v1/signatures/signatures.go, v1/worker.go, v1/workflow.go
Chord is a group of parallel tasks with a joint callback.
When all tasks in a group complete, the callback is triggered with aggregated results from the group.
=> Feature: Chords

integrationtests/amqp_amqp_test.go, integrationtests/amqp_memcache_test.go, integrationtests/amqp_redis_test.go, integrationtests/redis_memcache_test.go, integrationtests/redis_redis_test.go, integrationtests/testutils.go
Integration tests have been moved to a separate root level package and
split to multiple files for easier maintenance.
=> Split integration tests for easier management.

v1/backends/redis.go
Instead of using GET in a loop when retrieving states of group of tasks,
we now use MGET which does it all in one go and should provide a small
performance boost.
http://redis.io/commands/mget
=> Using MGET to retrieve multiple values.

v1/errors/errors.go
- use Panicf instead of Fatalf + manual panic which didn't work as stated
- use Printf instead of Fatalf in error which shouldn't kill whole application
=> A bit more accurate work with logging:

v1/brokers/redis.go
https://github.com/RichardKnop/machinery/issues/53
=> Fixing an issue with Redis broker and Quit method.

v1/worker.go
Reverts RichardKnop/machinery#76
=> Revert "Bug fix for error handling in worker"

v1/server.go, v1/server_test.go
'''
names := make([]string, len(server.registeredTasks))
for name := range server.registeredTasks {
names = append(names, name)
}
'''
the slice `names`  will be twice as large as expected
=> fix getRegisteredTasksNames slice append error

examples/send/send.go, examples/tasks/tasks.go, examples/worker/worker.go, v1/worker.go
Issue: https://github.com/RichardKnop/machinery/issues/96
When task panics, stack trace is printed to the log.
=> Print stack trace when task panics.

v1/backends/amqp.go, v1/backends/eager.go, v1/backends/memcache.go, v1/backends/mongodb.go, v1/backends/mongodb_test.go, v1/backends/mongodb_types.go, v1/backends/redis.go, v1/backends/result.go
Solves this issue: https://github.com/RichardKnop/machinery/issues/30
=> Chord Callback Idempotency Fix

README.md, examples/send/send.go, examples/worker/worker.go, integrationtests/amqp_amqp_test.go, integrationtests/amqp_memcache_test.go, integrationtests/amqp_redis_test.go, integrationtests/redis_get_pending_tasks_test.go, integrationtests/redis_memcache_test.go, integrationtests/redis_redis_test.go, integrationtests/redis_socket_test.go, integrationtests/test.go, integrationtests/worker_only_consumes_registered_tasks_test.go, v1/backends/amqp.go, v1/backends/amqp_test.go, v1/backends/mongodb_test.go, v1/brokers/amqp.go, v1/config/config.go, v1/config/config_test.go, v1/config/testconfig.yml, v1/factories_test.go, v1/server_test.go, v1/worker.go
AMQP settings wrapped in separate config struct
Added prefetch_count as configuration.
=> Refactored config

v1/brokers/redis.go, v1/worker.go
Hi Richard,
I created a PR which allow graceful shutdown of the worker respecting SIGINT/TERM signal. This is  done for redis broker. Please take a look and comment.
-Karthik
=> Handle Interrupt/TERM signal and shutdown worker gracefully.

v1/backends/async_result.go
I add three functions in this version.
The chord and chain tasks have the WaitWithTimeout features
=> add chord and chain WaitWithTimeout

example/tasks/tasks.go, v1/backends/mongodb.go
mongodb changes travis ci build with added support for mongodb result value to be in json.now we can have json in the result set of result.
=> Backend mongo json changes

example/tasks/tasks.go, v1/backends/mongodb.go
@RichardKnop  This changes is required to get the backend result into json format. i tested the integration test with go test command and i am getting success .if you have found anything please let me know.
=>  backend mongo json changes

example/machinery.go, v1/backends/async_result.go, v1/tasks/result.go, v1/worker.go
Added a non blocking LaunchAsync method to worker struct as alternative to blocking Launch.
=> Add a non blocking LaunchAsync method to worker

Makefile, README.md, v1/brokers/aws_sqs_export_test.go, v1/brokers/broker.go
Hello! I tried to improve code quality of project:
1. I fixed `make golint`: before it didn't fail build if issues were found
2. I tried to enable more linters in `gometalinter` (e.g. `errcheck`), but I couldn't: we need to fix too much issues to enable it.
3. I added code quality badges:
- [goreportcard](https://goreportcard.com/report/github.com/RichardKnop/machinery) - here are some issues from `golint` and `gocyclo`. I fixed all issues from `golint`, but didn't touch `gocyclo`.
- [golangci](https://golangci.com) - now it's only badge, if you want to check code quality in pull requests you can signup in it, it's free
=> code quality fixes & improvements

v1/tasks/state.go
change line #32 from "chord_trigerred" to "chord_triggered"
=> ISSUE-241 chord_triggered typo in tasks/state

.gitignore, v1/brokers/aws_sqs.go, v1/config/config.go
- added SQSConfig to config package
- NewAWSSQSBroker use SQS client if provided via config.Config.SQS
- receiveMessage use provided WaitTimeSeconds param if provided via config.Config.SQS
=> ISSUE-243: Support passing SQS options via config.Config

example/machinery.go, example/tasks/tasks.go, v1/tasks/reflect.go, v1/tasks/reflect_test.go, v1/tasks/result_test.go, v1/tasks/task.go, v1/tasks/task_test.go
Refactoring of reflection logic. Fixed few small bugs including:
https://github.com/RichardKnop/machinery/issues/254
=> Refactored reflection and fixed several small bugs.

Gopkg.lock, Gopkg.toml, example/machinery.go, integration-tests/suite_test.go, integration-tests/worker_only_consumes_registered_tasks_test.go, v1/server.go, v1/tasks/signature.go, v1/tasks/workflow.go, v1/tasks/workflow_test.go, vendor/github.com/satori/go.uuid/README.md, vendor/github.com/satori/go.uuid/codec_test.go, vendor/github.com/satori/go.uuid/generator.go, vendor/github.com/satori/go.uuid/generator_test.go, vendor/github.com/satori/go.uuid/uuid_test.go
I bumped `go.uuid` to `master` and ran `dep ensure`.
Unfortunately, there are breaking changes to `NewSignature()`, `NewGroup()`, `NewChord()` and `NewChain()`, because these functions also return an error if uuid generation fails.
Closes #259
=> Pin go.uuid to master (36e9d2ebbde5e3f13ab2e25625fd453271d6522e)

README.md
examples for:
- sqs integration test
- manually configured sqs client
=> README SQS Update

v1/backends/dynamodb.go, v1/brokers/aws_sqs_test.go, v1/config/config.go
For more details of the error, please check the conversations in https://github.com/udacity/machinery/pull/14
=> Fix the envconfig format of DynamoDBConfig and a bug of DynamoDB

v1/brokers/aws_sqs.go
Done by validating the SendMessageInput.DelaySeconds field before making the API call
=> Save an AWS SQS API call 

v1/backends/mongodb.go, v1/tasks/state.go
- added TaskName to state.TaskResult
- updated state.NewPendingTaskState to include TaskName
- updated mgo backend to include task_name in SetStatePending
- use encoding/json to decode json strings in []*tasks.TaskResult
- assign JSON result type as lowercase "json"
#284
=> #284 - state.TaskResult.TaskName

v1/backends/mongodb.go
- Added support for dialing with TLSConfig if provided via Config.
- Refactored mongo connect to return an Op struct containing a copied session & collection references
- Refactored mongo operations to use Op.Do wrapping the mgo logic in an enclosing func to defer session close.
After running machinery on a kubernetes stack for a few days we started seeing "Closed Explicitly" errors coming from mgo.  It sounds like a common consensus for avoiding this error w/ mgo in concurrent applications is to use session.Copy() for operations, or possibly refreshing the original session, instead of reusing the original session indefinitely.   
https://github.com/go-mgo/mgo/issues/166#issuecomment-144103844
=> Mongo - TSLConfig support & session.Copy

v1/log/log.go, vendor/github.com/RichardKnop/logging/logger.go
After https://github.com/RichardKnop/logging/pull/1
I think it's possible to add DEBUG level here.
I'm not sure this PR is ok so I'm asking for review and I will improve it if needed.
=> Added DEBUG level

v1/backends/redis/redis.go, v1/backends/redis/redis_test.go
Hello, 
Here a PR to keep data between change step for redis backend. 
Before, we create a new TaskState object (without name, createdAt property) and insert it into redis backend.
=> keep task data between state

v1/brokers/iface/interfaces.go, v1/brokers/redis/redis.go, v1/server.go, v1/server_test.go, v1/worker.go
Referring https://github.com/RichardKnop/machinery/issues/303
This implementation adds new method for server `NewCustomQueueWorker` accepting one more parameter.
This parameter is the custom queue to consume.
Actually this implementation works only for Redis.
Do you think this implementation is good enough?
=> Redis CustomQueue

v1/brokers/redis/redis.go, v1/worker.go
Too many logs are unacceptable after application custom log.
=> Reduce some log level.

README.md
Minor typo maybe cause serious problem in scenario of multy tasks.
=> Update readme typo error.

v1/worker.go
That will be convenient for manage multi pair of server and worker.
=> Add GetServer() function for Worker.

v1/factories.go, v1/factories_test.go
Fixes #332 
Disable Strict SQS name check if special environment variable `DISABLE_STRICT_SQS_CHECK` is set
=> Fixes #332 Allow usage of local/simulated(non-aws) SQS with special environment variable

v1/server.go
A way to initiate a Server with a custom broker/result server.
=> Init a server with custom broker/backend

v1/brokers/amqp/amqp.go
Fix for [issue 349](https://github.com/RichardKnop/machinery/issues/349)
=> AMQP Worker - use Custom queue, fallback to default if not exists

v1/server.go
Call a function before publishing a message
=> Server - Pre publish handler

v1/tasks/validate.go
=> Fix typo in error message

integration-tests/gcppubsub_redis_test.go, v1/brokers/gcppubsub/gcp_pubsub.go
Moving validations to the creation of the broker allows to fail fast on application boot and removes the requirement of validating if the topic exists on each Publish. Validating the topic is adding to the response time and slows the Publish by around 133ms on average, with a p90 of 161ms.
=> Move validation to broker creation.

go.mod, go.sum, v1/backends/mongo/mongodb.go, v1/config/config.go, v1/factories_test.go
Mongodb like to make breaking changes even in RC releases.
Updated to use new import path.
Fix new client constructor
=> Update mongo db driver version to 1.0.0rc2

go.mod, go.sum
=> Upgrade to mongodb v1.0.0

v1/config/config.go
=> fix: "true" spell wrong

go.mod, v1/backends/null/null.go, v1/brokers/amqp/amqp.go, v1/factories.go
disconnected, remove the connection for the queue, so that
GetOrOpenConnection() will retry the connection.
Fix #411
=> In AMQP broker, when trying to reconnect, after connection was

v1/brokers/sqs/sqs.go
=> fixed panic in SQS broker

.gitignore, integration-tests/gcppubsub_redis_test.go, v1/backends/amqp/amqp.go, v1/backends/dynamodb/dynamodb.go, v1/backends/eager/eager.go, v1/backends/iface/interfaces.go, v1/backends/memcache/memcache.go, v1/backends/mongo/mongodb.go, v1/backends/redis/redis.go, v1/brokers/amqp/amqp.go, v1/brokers/eager/eager.go, v1/brokers/gcppubsub/gcp_pubsub.go, v1/brokers/iface/interfaces.go, v1/brokers/redis/redis.go, v1/brokers/sqs/sqs.go, v1/common/amqp/amqp.go, v1/common/redis/redis.go, v1/config/config.go, v1/factories.go, v1/worker.go
refact BrokerFactory() and BackendFactory(), let it is  pluggability.
=> refact factory

v1/config/config.go
=> Fix typo in config.go

v1/brokers/redis/redis.go
=> Added logging line to the redis broker when task is not registered

v1/tasks/reflect.go
When `json.Marshal` is used []byte and []uint8 will be encoded with base64 but they won't be decoded back so the type value type will be string that can't be converted to a []uint8.  
Beside that I've also added support for []byte because it's technically the same type and most people will use []byte over []uint8 probably :).  
Issue related to this: #382
=> Added support for []byte and fixed []uint8 value types

go.mod, go.sum
try to fix issue #461 
verify: `go mod download` and run as expected
=> Fix issue #461: replace thrift.git using github repo

v1/backends/mongo/mongodb.go, v1/factories.go, v1/factories_test.go
Fixed a problematic unit test that tried to connect to mongodb.
Unit tests should not be making any connections to databases etc, that should only be done in integration tests.
=> fix: fixed a unit test which actually tried to connect to mongo

v1/brokers/errs/errors.go, v1/brokers/sqs/sqs.go, v1/tasks/signature.go, v1/worker.go
useful when we want to sqs to send messages to dlq on repeated
consumption and processing failure of erroneous messages
for issue https://github.com/RichardKnop/machinery/issues/471
=> add option to stop task deletion

README.md, v2/package.go, v2/server.go, v2/server_test.go, v2/worker.go
=>  feature: initial V2 experiment commit

v1/brokers/amqp/amqp.go
=> Fix typo 'occured' to 'occurred'

v1/backends/redis/goredis.go, v1/brokers/redis/goredis.go, v1/config/config.go
=> Support redis sentinel-backed FailoverClient

integration-tests/amqp_get_pending_tasks_test.go, v1/brokers/amqp/amqp.go
Implement GetPendingTasks for RabbitMQ, to match the Redis one. Comes with an integration test too.
=> feat: Implement GetPendingTasks for AMPQ broker

example/config.yml
=> Fix: Use same Queue in example

v1/worker.go, v1/worker_test.go, v2/worker.go
This PR fixes Issue https://github.com/RichardKnop/machinery/issues/438
=> Redact url

v1/backends/dynamodb/dynamodb.go, v1/backends/dynamodb/dynamodb_export_test.go, v1/backends/dynamodb/dynamodb_test.go
This PR fixes https://github.com/RichardKnop/machinery/issues/536
https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#DynamoDB.BatchGetItem
Using batch operations to get states is more efficient and prevents resource exhaustion when a group contains large number of tasks (Ex: > 2k tasks). This is especially important since on every task completion we check the state of every other task in a goroutine. This results in quadratic number of API calls by the time the group completes.
The fix is to use batch operations provided by AWS. DynamoDB limits the number of items in a batch to 100 and may not always return all requested keys. So a retry with backoff (with limit) is included.
Also improved some tests and fixed a potential deadlock (writing to an unread channel)
=> [DynamoDB] Batch fetch task states

v1/backends/redis/redis.go
fix redigo connection blocking issue #546
=> fix: reuse connection to prevent philosopher dining problem

README.md
=> Fix #339 - Document argument passing behavior with chains

v1/backends/redis/goredis.go, v1/backends/redis/redis.go
Set TTL for the key at the same time when setting the value
=> Fix 413 - (Redis) Simplify TTL

v1/factories.go
=> Support redis ssl

v1/brokers/redis/redis.go
Reverts RichardKnop/machinery#580
=> Revert "ensure consuming blocked by previous task (#559)"

v1/brokers/redis/redis.go
goredis implementation supported this long time ago, which should also be supported in redigo implementation
=> feat: Support customized delayed tasks key in redigo implementation

.deepsource.toml, integration-tests/gcppubsub_redis_test.go, integration-tests/redis_redis_test.go, v1/backends/eager/eager.go, v1/backends/eager/eager_test.go, v1/backends/mongo/mongodb.go, v1/brokers/amqp/amqp.go, v1/brokers/sqs/sqs_test.go, v1/factories.go, v1/tasks/reflect.go, v1/worker.go, v2/worker.go
This pull request fixes some of the issues raised by [DeepSource](https://deepsource.io/gh/sourya-deepsource/machinery/) on my fork of this repo.
Some issues were automatically fixed by DeepSource, while I fixed some of them by hand.
This PR also contains a `.deepsource.toml`, in case you want to run continuous quality analyses on your repository. If you wish to do so, you can follow these steps:
1. Merge this PR.
2. Signup on DeepSource [here](https://deepsource.io/signup).
3. Activate analysis on your repo [here](https://deepsource.io/gh/RichardKnop/machinery).
If you don't want to use DeepSource, I can edit the PR to remove the `.deepsource.toml` file.
=> Fix quality issues

example/machinery.go, v1/brokers/sqs/sqs_export_test.go, v1/brokers/sqs/sqs_test.go, v1/factories.go, v1/server_test.go, v1/worker.go, v1/worker_test.go, v2/server.go, v2/server_test.go, v2/worker.go, v2/worker_test.go
https://github.com/RichardKnop/machinery/issues/610
=> fix: make sure eager lock is defaulted to

v1/locks/eager/eager.go, v1/locks/redis/redis.go
add expiration for redis lock key. fix the bug of eager lock
=> add expiration for redis lock key. fix the bug of eager lock

v1/locks/redis/redis.go
=> fix redis password with special char

v1/locks/redis/redis.go
Previously, expiration was set as a duration constructed from an absolute timestamp. This led to a bug that set the expiration time for most entries as over 50 years in the future. This PR updates it to a value relative to the current time.
I have taken the liberty of renaming some local variables to make this distinction clearer.
=> Fix redis lock expiration.

README.md, v2/example/amqp/main.go, v2/example/go-redis/main.go, v2/example/redigo/main.go
1. variable name  and package name fix
2. `app.Run` ignore error with _
3. `time.Duration` No need to show the statement anymore
=> v2_example_fix

v1/brokers/redis/goredis.go, v2/brokers/redis/goredis.go
=> brokers: add IgnoreWhenTaskNotRegistered option for goredis

v1/backends/redis/goredis.go, v1/brokers/redis/goredis.go, v1/locks/redis/redis.go, v2/backends/redis/goredis.go, v2/brokers/redis/goredis.go, v2/locks/redis/redis.go
fix this issue: https://github.com/RichardKnop/machinery/issues/726
=> fix: redis password with '@'

v1/backends/dynamodb/dynamodb.go, v2/backends/dynamodb/dynamodb.go
checkRequiredTablesIfExist() fails with error: 'task table doesn't exist' due to (*dynamodbiface.DynamoDBAPI).ListTables doesn't retrieve full list of tables. You should use for{...}. This PR fixes this bug.
=> fix (*dynamodbiface.DynamoDBAPI).ListTables

v1/common/redis.go, v1/config/config.go, v2/common/redis.go, v2/config/config.go
Add a redis config variable to pass redis connection name to redigo/redis
=> Add redis client name config option

v2/backends/mongo/mongodb.go
currently `ResultsExpireIn` does not work for mongodb results backend, because the indexed fields do not contain a date.
=> fix ttl index for mongodb results backend

v2/backends/redis/goredis.go, v2/brokers/redis/goredis.go, v2/config/config.go, v2/locks/redis/redis.go
fix v2 (redis): redis sentinel Authentication required bug
=> fix v2 (redis): redis sentinel Authentication required bug

v1/brokers/redis/redis.go, v2/brokers/redis/redis.go
fix redis consumer problem
https://github.com/RichardKnop/machinery/issues/643
=> fix redis consumer bug

v1/backends/redis/goredis.go, v1/backends/redis/redis.go, v1/brokers/redis/goredis.go, v1/brokers/redis/redis.go, v1/common/redis.go, v1/factories.go, v1/factories_test.go, v2/backends/redis/goredis.go, v2/backends/redis/redis.go, v2/backends/redis/redis_test.go, v2/brokers/redis/goredis.go, v2/brokers/redis/redis.go, v2/common/redis.go, v2/example/redigo/main.go
please add redis username auth.
redis url like this `redis://user:password@host:port`
some one add issue in https://github.com/RichardKnop/machinery/issues/214
=> support redis username
